defaults:
  - env_go2Piper
  - tasks@tasks.locomotion: local_2d_vel
  - _self_

cfg:
  env:
    num_observations: 63
    num_privileged_obs: 142
tasks:
  locomotion:
    feet_sensor_indices:
      - 0
      - 1
      - 2
      - 3
constraints:
  action_rate:
    penalty_weight: -0.02
  feet_drag:
    penalty_weight: -0.01
  energy:
    penalty_weight: -1e-6
