defaults:
  - combo_go2Piper_pickle_reaching_velcmd_arm_swing
  - _self_

# 覆盖环境类，使用新的机械臂摆动环境
_target_: legged_gym.env.isaacgym.env_velcmd_arm_swing.IsaacGymEnvVelCmdArmSwing

headless: True



cfg:
  init_state:
    pos_noise:
      - 0.1
      - 0.1
      - 0.0
    euler_noise:
      - 0.05
      - 0.05
      - 0.5
  env:
    num_privileged_obs: ${eval:"192 + len(${env.tasks.reaching.target_obs_times})*9 + 7 + 6"}
    # 基础privileged观测(192) + task观测(动态) + 新增观测(7) + baselink速度指令(3)
    num_envs: 2048

  # 课程学习配置
  curriculum:
    stage: 1                    # 初始阶段
    transition_steps: 20000000   # 阶段转换步数（2000万步）
    arm_swing_enabled: false    # 初始不启用机械臂摆动
    arm_swing_amplitude: 0.5    # 摆动幅度

  domain_rand:
    transport_robots: true
    transport_interval_s: 4.0
    transport_pos_noise_std:
      _target_: torch.tensor
      device: ${....sim_device}
      data:
        - 0.1
        - 0.1
        - 0.01
    transport_euler_noise_std:
      _target_: torch.tensor
      device: ${....sim_device}
      data:
        - 0.01
        - 0.01
        - 0.5
    randomize_dof_damping: true
    dof_damping_range:
      - 0.01
      - 0.5
    randomize_dof_friction: true
    dof_friction_range:
      - 0.0
      - 0.05
    friction_range:
      - 0.1
      - 8.0
    added_mass_range:
      - -0.25
      - 0.25
    base_com_range:
      data:
        - - -0.1
          - -0.1
          - -0.1
        - - 0.1
          - 0.1
          - 0.1
    randomize_rigid_body_masses:
      - base
      - link1
      - link3
      - link5
      - link6
    randomize_rigid_body_com:
      - base
      - link1
      - link3
      - link5
      - link6
    randomize_restitution_rigid_bodies: []