defaults:
  - combo_go2Piper_pickle_reaching_velcmd_arm_swing
  - _self_

# 覆盖环境类，使用新的机械臂摆动环境
_target_: legged_gym.env.isaacgym.env_add_baseinfo.IsaacGymEnv

headless: False

ctrl_delay:
  data:
  # quadruped
   - 0.020
   - 0.020
   - 0.020
   - 0.020
   - 0.020
   - 0.020
   - 0.020
   - 0.020
   - 0.020
   - 0.020
   - 0.020
   - 0.020

state_obs:
  dof_pos:
    dim: 18
  dof_vel:
    dim: 18
privileged_state_obs:
  dof_pos:
    dim: 18
  dof_vel:
    dim: 18


cfg:
  init_state:
    pos_noise:
      - 0.1
      - 0.1
      - 0.0
    euler_noise:
      - 0.05
      - 0.05
      - 0.5
  env:
    num_privileged_obs: ${eval:"193 + len(${env.tasks.reaching.target_obs_times})*9"}
    # 基础privileged观测(192) + ee_task + locomotion_task
    num_envs: 4


  domain_rand:
    transport_robots: true
    transport_interval_s: 4.0
    transport_pos_noise_std:
      _target_: torch.tensor
      device: ${....sim_device}
      data:
        - 0.1
        - 0.1
        - 0.01
    transport_euler_noise_std:
      _target_: torch.tensor
      device: ${....sim_device}
      data:
        - 0.01
        - 0.01
        - 0.5
    randomize_dof_damping: true
    dof_damping_range:
      - 0.01
      - 0.5
    randomize_dof_friction: true
    dof_friction_range:
      - 0.0
      - 0.05
    friction_range:
      - 0.1
      - 8.0
    added_mass_range:
      - -0.25
      - 0.25
    base_com_range:
      data:
        - - -0.1
          - -0.1
          - -0.1
        - - 0.1
          - 0.1
          - 0.1
    randomize_rigid_body_masses:
      - base
      - link1
      - link3
      - link5
      - link6
    randomize_rigid_body_com:
      - base
      - link1
      - link3
      - link5
      - link6
    randomize_restitution_rigid_bodies: []